server:
  port: 80

spring:
  application:
    name: spring-shop

  devtools:
    restart:
      enabled: false

    livereload:
      enabled: false

  thymeleaf:
    cache: false

  security:
    user:
      name: test@test.com
      password: 1111

  ####################################
  # 데이터베이스 설정
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springshop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234567890

  ####################################
  # JPA 설정
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜표기를 스네이크 표기로 변환
    show-sql: true          # SQL 구문 보이기
    properties:
      hibernate:
        format_sql: true    # 포멧 처리해서 보이기
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 버전 사용

####################################
# Log Setting
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace